src/java/br/com/fenaconcd/controllers/FuncionarioController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fenaconcd.controllers;

import br.com.fenaconcd.entities.Funcionario;
import br.com.fenaconcd.enums.Cargo;
import br.com.fenaconcd.enums.Situacao;
import br.com.fenaconcd.persistance.FuncionarioFacade;
import br.com.fenaconcd.utils.JsfUtil;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Collection;
import java.util.Date;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.component.html.HtmlDataTable;
import javax.faces.context.FacesContext;

/**
 * Controlador responsável por controlar a persistência e listagem dos dados dos funcionarios
 * @author Leonardo
 */
@ManagedBean
@ViewScoped
public class FuncionarioController implements Serializable {

    @EJB
    private FuncionarioFacade ff;
    private Collection<Funcionario> funcionarios;
    private Funcionario funcionario;

    public FuncionarioController() {
        setFuncionario(new Funcionario());
    }

    /**
     * Anotacao @PostConstruct faz com que este metodo seja executado logo apos o construtor. 
     * Responsavel por popular a listagem dos funcionarios fazendo uma consulta ao banco 
     */
    @PostConstruct
    public void populate() {
        setFuncionarios(getFf().findAll());
    }

    /**
     * Persiste no banco uma nova instancia de funcionario ou informa ao usuario erro na populacao do supervisor.
     * @return Encaminha para a listagem dos funcionarios ou atualiza a pagina informando o aviso.
     */
    public String cadastrar() {
        cargoSemSupervisor();

        if (isSupervisorCorreto()) {
            getFf().create(getFuncionario());
            JsfUtil.addSuccessMessage(getFuncionario().getNome() + " cadastrado(a) com sucesso.");
            return "/restricted/listagemFuncionarios.xhtml";
        } else {
            return "/main/cadastroFuncionario.xhtml";
        }
    }

    /**
     * Responsavel por verificar o tipo de supervisor para cada cargo
     * @return 
     */
    public boolean isSupervisorCorreto() {
        boolean supervisorCorreto = true;

        switch (getFuncionario().getCargo().getDescricao()) {
            case "Estagiário":
                if (getFuncionario().getSupervisor() != Cargo.ANALISTA) {
                    JsfUtil.addErrorMessage("Somente um Analista pode supervisionar um Estagiário");
                    supervisorCorreto = false;
                }
                break;
            case "Técnico":
                if (getFuncionario().getSupervisor() != Cargo.ANALISTA) {
                    JsfUtil.addErrorMessage("Somente um Analista pode supervisionar um Estagiário");
                    supervisorCorreto = false;
                }
                break;
            case "Analista":
                if (getFuncionario().getSupervisor() != Cargo.GERENTE) {
                    JsfUtil.addErrorMessage("Somente um Gerente pode supervisionar um Analista");
                    supervisorCorreto = false;
                }
                break;
        }

        return supervisorCorreto;
    }

    /**
     * Edita uma instancia de Funcionario no Banco de dados
     * @param func
     * @return Recarrega a pagina informando o aviso de sucesso
     */
    public String editar(Funcionario func) {
        getFf().edit(func);
        JsfUtil.addSuccessMessage(func.getNome() + " editado(a) com sucesso.");
        return "/restricted/listagemFuncionarios.xhtml";
    }

    /**
     * Exclui uma instancia de Funcionario do Banco de Dados
     * @param func
     * @return Recarrega a pagina informando o aviso de sucesso
     */
    public String excluir(Funcionario func) {
        getFf().remove(func);
        JsfUtil.addSuccessMessage(func.getNome() + " excluído(a) com sucesso.");
        return "/restricted/listagemFuncionarios.xhtml";
    }

    /**
     * Responsavel por encaminhar para a tela onde as ferias serao cadastradas. Contudo, antes disso verifica se 
     * tal funcionario esta habilitado para tirar ferias. 
     * @param funcionario
     * @return Encaminha para cadastro de ferias ou recarrega a pagina informando o aviso
     */
    public String transferirParaCadastroFerias(Funcionario funcionario) {
        Date dataAdmissao = funcionario.getDataAdmissao();
        Calendar cal = Calendar.getInstance();
        cal.setTime(dataAdmissao);
        int ano = cal.get(Calendar.YEAR);
        int anoAtual = Calendar.getInstance().get(Calendar.YEAR);

        if (ano == anoAtual) {
            JsfUtil.addErrorMessage("O funcionário ainda não pode tirar férias");
            return "/restricted/listagemFuncionarios.xhtml";
        } else {
            FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("funcionario", funcionario);
            return "/restricted/cadastroFerias.xhtml";
        }
    }

    /**
     * Responsavel por chamar o metodo que converte a data para que esta apareca no formato brasileiro
     * @param data
     * @return 
     */
    public String converterData(Date data) {
        return JsfUtil.converterData(data);
    }
    
    /**
     * Responsavel por transformar o enum de representacao de um Cargo
     * @return Collection de cargo
     */
    public Collection<Cargo> getTiposCargo() {
        return Arrays.asList(Cargo.values());
    }

    /**
     * Responsavel por transformar o enum de representacao de um Situacao
     * @return Collection de situacao
     */
    public Collection<Situacao> getTiposSituacao() {
        return Arrays.asList(Situacao.values());
    }

    /**
     * Responsavel por avancar uma pagina da listagem
     * @param hdt 
     */
    public void avancar(HtmlDataTable hdt) {
        hdt.setFirst(hdt.getFirst() + hdt.getRows());
    }

    /**
     * Responsavel por retornar uma pagina da listagem
     * @param hdt 
     */
    public void retornar(HtmlDataTable hdt) {
        hdt.setFirst(hdt.getFirst() - hdt.getRows());
    }

    /**
     * Responsavel por anular o campo supervisor para um funcionario do tipo gerente, visto que esse nao possui supervisor
     */
    public void cargoSemSupervisor() {
        if (getFuncionario().getCargo() == Cargo.GERENTE) {
            getFuncionario().setSupervisor(null);
        }
    }

    /**
     * Responsavel por filtrar a listagem de funcionarios de acordo com o nome
     */
    public void filtrar() {
        Collection<Funcionario> filtro = new ArrayList<>();
        String nomeFuncionario = getFuncionario().getNome();
        if (nomeFuncionario.isEmpty()) {
            setFuncionarios(getFf().findAll());
        } else {
            for (Funcionario func : getFf().findAll()) {
                if (func.getNome().toLowerCase().contains(nomeFuncionario.toLowerCase())) {
                    filtro.add(func);
                }
            }
            setFuncionarios(filtro);
        }
    }

    
    //GETTERS AND SETTERS 
    
    public FuncionarioFacade getFf() {
        return ff;
    }

    public void setFf(FuncionarioFacade ff) {
        this.ff = ff;
    }

    public Funcionario getFuncionario() {
        return funcionario;
    }

    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

    public Collection<Funcionario> getFuncionarios() {
        return funcionarios;
    }

    public void setFuncionarios(Collection<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }

}

src/java/br/com/fenaconcd/controllers/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fenaconcd.controllers;

import br.com.fenaconcd.entities.Usuario;
import br.com.fenaconcd.entities.UsuarioBO;
import br.com.fenaconcd.utils.JsfUtil;
import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

/**
 * Controlador responsavel por gerenciar os dados de login do usuario
 * @author Leonardo
 */
@ManagedBean
@ViewScoped
public class LoginController implements Serializable{
    private boolean loggedIn;
    private Usuario usuarioLogado;
    private String login;
    private String senha;
    
    /**
     * Responsavel por autenticar o usuario no sistema
     * @return 
     */
    public String doLogin(){
                             
         Usuario usuarioFound = (Usuario) new UsuarioBO().isUsuarioReadyToLogin(login, senha);
                     
         if (usuarioFound == null){
               JsfUtil.addErrorMessage("Login ou senha errado(s). Tente novamente !");
               FacesContext.getCurrentInstance().validationFailed();
               return "/main/login.xhtml";     
         }else{
           loggedIn = true;
           usuarioLogado = usuarioFound;
           return "/restricted/cadastroUsuario.xhtml";
         }
    }
    
    /**
     * Responsavel por desautenticar o usuario do sistema
     * @return 
     */
    public String doLogout(){
    
         //Setamos a variável usuarioLogado como nulo, ou seja, limpamos
        //os dados do usuário que estava logado e depois setamos a variável
        //loggedIn como false para sinalizar que o usuário não está mais           
        //logado
         usuarioLogado = null;
         loggedIn = false;
         //Mostramos um mensagem ao usuário e redirecionamos ele para a         //página de login
         JsfUtil.addSuccessMessage("Logout realizado com sucesso !");
         return "/restricted/login.xhtml";
  }

    public boolean isLoggedIn() {
        return loggedIn;
    }

    public void setLoggedIn(boolean loggedIn) {
        this.loggedIn = loggedIn;
    }

    public Usuario getUsuarioLogado() {
        return usuarioLogado;
    }

    public void setUsuarioLogado(Usuario usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }
    
    
    
}

web/cadastroFuncionario.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui">
    <ui:include src="/resources/content/metadata.xhtml" />
    <h:body>
        <div class="center-block" style="width: 90%">
            <ui:include src="/resources/content/header.xhtml" />

            <p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" />

            <!--CADASTRO DO FUNCIONARIO-->
            <div class="tab-content">
                <div class="tab-pane active" id="cadastro" role="tabpanel">
                    <br/>
                    <div align="center">
                        <h:form class="form-horizontal">
                            <div align="center">
                                <h4>Identificação do Funcionário</h4>    
                            </div>
                            <br/>
                            <div class="form-group">
                                <!--CARGO-->
                                <h:outputLabel class="col-sm-2 control-label" 
                                               for="cargo" value="Cargo" />
                                <div class="col-sm-3">
                                    <h:selectOneMenu class="form-control" 
                                                     id="cargo"
                                                     title="Cargo."
                                                     value="#{funcionarioController.funcionario.cargo}">
                                        <f:selectItems itemLabel="#{cargo.descricao}" 
                                                       itemValue="#{cargo}"
                                                       value="#{funcionarioController.tiposCargo}" 
                                                       var="cargo" />
                                        <f:ajax render="@form"/>
                                    </h:selectOneMenu>
                                </div>
                                <!--Carga Horaria-->
                                <h:outputLabel class="col-sm-2 control-label" for="cargaHoraria"
                                               value="Carga Horária" />
                                <div class="col-sm-3">
                                    <h:inputText class="form-control" id="cargaHoraria"
                                                 maxlength="2"
                                                 required="true"
                                                 requiredMessage="Preencha a carga horária."
                                                 title="Carga horária."
                                                 value="#{funcionarioController.funcionario.cargaHoraria}">
                                        <f:passThroughAttributes 
                                            value="#{{'placeholder':'Ex.: 44', 
                                                     'required':'true',
                                                     'type':'number'}}" />
                                    </h:inputText>
                                </div>
                            </div>

                            <div class="form-group">
                                <!--Nome-->
                                <h:outputLabel class="col-sm-2 control-label" for="nome"
                                               value="Nome" />
                                <div class="col-sm-3">
                                    <h:inputText class="form-control" id="numeroSerie"
                                                 maxlength="20"
                                                 required="true"
                                                 requiredMessage="Preencha o nome."
                                                 title="Nome."
                                                 value="#{funcionarioController.funcionario.nome}">
                                        <f:passThroughAttributes 
                                            value="#{{'autofocus':'autofocus',
                                                     'placeholder':'Ex.: Paulo Ferreira',
                                                     'required':'true'}}" />
                                    </h:inputText>
                                </div>
                                <!--SITUACAO-->
                                <h:outputLabel class="col-sm-2 control-label" 
                                               for="tipo" value="Situação" />
                                <div class="col-sm-3">
                                    <h:selectOneMenu class="form-control" 
                                                     id="tipo"
                                                     title="Situação."
                                                     value="#{funcionarioController.funcionario.situacao}">
                                        <f:selectItems itemLabel="#{situacao.descricao}" 
                                                       itemValue="#{situacao}"
                                                       value="#{funcionarioController.tiposSituacao}" 
                                                       var="situacao" />
                                    </h:selectOneMenu>
                                </div>
                            </div>
                            <!--ENDEREÇO COMPLETO-->
                            <div class="form-group">
                                <h:outputLabel class="col-sm-2 control-label" 
                                               for="endCompleto" value="Endereço Completo" />
                                <div class="col-sm-8">
                                    <h:inputText class="form-control" id="endCompleto"
                                                 required="true"
                                                 requiredMessage="Preencha o endereço."
                                                 title="Endereço."
                                                 value="#{funcionarioController.funcionario.endCompleto}">
                                        <f:passThroughAttributes 
                                            value="#{{'autofocus':'autofocus',
                                                     'placeholder':'Ex.: Quadra 2 Conjunto Z apt 201', 
                                                     'required':'true'}}" />
                                    </h:inputText>
                                </div> 
                            </div>
                            <!--DATA ADMISSÃO-->
                            <div class="form-group">
                                <h:outputLabel class="col-sm-2 control-label" for="dataAdmissao"
                                               value="Data de admissão" />
                                <div class="col-sm-3">
                                    <h:inputText class="form-control" id="dataAdmissao"
                                                 required="true"
                                                 requiredMessage="Preencha a data de admissão."
                                                 title="Data de aquisição"
                                                 value="#{funcionarioController.funcionario.dataAdmissao}">
                                        <f:convertDateTime 
                                            locale="pt-BR" 
                                            pattern="yyyy-MM-dd" 
                                            timeStyle="short" 
                                            timeZone="Brazil/East" 
                                            type="date" />
                                        <f:passThroughAttributes 
                                            value="#{{'placeholder':'Data de admissão', 
                                                     'required':'true',
                                                     'type':'date'}}"/>
                                    </h:inputText>
                                </div>
                                <!--CPF-->
                                <h:outputLabel class="col-sm-2 control-label" for="cpf"
                                               value="CPF" />
                                <div class="col-sm-3">
                                    <h:inputText class="form-control cpf" id="cpf"
                                                 maxlength="14"
                                                 required="true"
                                                 requiredMessage="000.000.000-00."
                                                 title="CPF do responsável."
                                                 value="#{funcionarioController.funcionario.CPF}">
                                        <f:passThroughAttributes 
                                            value="#{{'autofocus':'autofocus',
                                                     'placeholder':'Ex.: 000.000.000-00',
                                                     'required':'true'}}" />
                                    </h:inputText>
                                </div>
                            </div>
                            <!--SUPERVISOR-->
                            <h:panelGroup layout="block" rendered="#{funcionarioController.funcionario.cargo.descricao != 'Gerente'}" binding="#{grupoCargo}" 
                                  id="grupoCargo">
                                <div class="form-group">                             
                                    <h:outputLabel class="col-sm-2 control-label" 
                                                   for="supervisor" value="Supervisor" />
                                    <div class="col-sm-3">
                                        <h:selectOneMenu class="form-control" 
                                                         id="supervisor"
                                                         title="Supervisor."
                                                         value="#{funcionarioController.funcionario.supervisor}">
                                            <f:selectItems itemLabel="#{cargo.descricao}" 
                                                           itemValue="#{cargo}"
                                                           value="#{funcionarioController.tiposCargo}" 
                                                           var="cargo" />
                                        </h:selectOneMenu>
                                    </div>
                                </div>
                            </h:panelGroup>
                            <br/>

                            <!--CADASTRAR-->
                            <div class="form-group">
                                <div class="col-sm-1">
                                    <h:commandButton action="#{funcionarioController.cadastrar()}"
                                                     class="btn btn-success" 
                                                     value="Cadastrar">
                                    </h:commandButton>
                                </div>
                            </div>
                        </h:form>
                    </div>
                </div> 
            </div>
            <ui:include src="/resources/content/footer.xhtml" />
        </div> 
    </h:body>
</html>

web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui">
    <ui:include src="/resources/content/metadata.xhtml" />
    <body>
        <div class="center-block" style="width: 90%">
            <ui:include src="/resources/content/header.xhtml"/>

            <p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" />
            
            <h:panelGroup>
                <div class="center-block well well-lg" style="margin-top: 23px; width: 45%">
                    <h:form class="form-horizontal">

                        <div class="form-group">
                            <h:outputLabel class="col-sm-2 control-label" for="login" 
                                           value="Login" />
                            <div class="col-sm-10">
                                <h:inputText class="form-control" id="login"
                                             maxlength="14"
                                             required="true"
                                             requiredMessage="Preencha o login."
                                             value="#{loginController.login}">
                                </h:inputText>
                            </div>
                        </div>
                        <div class="form-group">
                            <h:outputLabel class="col-sm-2 control-label" for="senha"
                                           value="Senha" />
                            <div class="col-sm-10">
                                <h:inputSecret class="form-control" id="senha" 
                                               required="true"
                                               requiredMessage="Preencha o campo senha."
                                               value="#{loginController.senha}">
                                </h:inputSecret>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <h:commandButton 
                                    class="btn btn-default"
                                    value="Entrar" 
                                    action="#{loginController.doLogin()}"/>
                            </div>
                        </div>
                    </h:form>
                </div>
            </h:panelGroup>
            <ui:include src="/resources/content/footer.xhtml"/>
        </div>
    </body>
</html>